language: python

#caching packages
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"
  - "3.6"

before_install:
  - pip install --upgrade setuptools wheel
  - pip install -r requirements.txt -r tests/tests-requirements.txt

install:
  - pip install -e .

script:
  - py.test tests/units