language: python
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '2.7'
- '3.6'
before_install:
- pip install --upgrade setuptools wheel
- pip install -U -r requirements.txt -r tests/tests-requirements.txt
install:
- python setup.py develop
script:
- pytest --cov=perfcounters --capture=sys
after_success:
- coveralls
deploy:
  provider: pypi
  user: elie
  password:
    secure: fxLyttr1MO6Cr4mE55y8hG5PVRdrujd62Swhd6Px+Scq9U0XbQ2IIs/UJB8PkJ5HGpseSM8n7QpLxxadkTqhInWujagFja5ArjNPUukHe9sSMT1VScvTc9dgyV49ziR8/9bqXioD8Bke7IDgAAC1M21gcfDY+2Qq7hsPQMYzq3BqGzkFOSIWDWrrdVxf5QmbxhInM0GzoVVyZFQGqgcxiphx6toB7jd/yYm6KZjuW1aKhclxIa7NLxWdspGK3FayXMmcmcbRc44Ibn6exwIanDw+bDZ4T4hVjegs0p9re7VhOc5bcrnu7t0slwjGsjgLSYB4hAJykZLrOGinAyFI8lEFcEDA3QVequ2ActwbGiHGIwCTf/izMN/XcHjtQd1172h6aix5Wa15oxwJ7g7NgQw6Sy0ISuGIyZo0YHImrkoUI1gMMDqOctbTTPLHuL3hxlJ5RsnmkMN8Mxpu25P702dbExGHZ6ODzGixsJU8co8uQsBFAJowijUEd2R2lPwbc0twe5BevIF1IuO78XD+IYcj7DM2qAXhxtsSBe3wbZTBP+XjLBuRxkEZrfFwlTAaLbU7ektMJMgw+BjclMLDYCpxxIpsgZPxzSqThEJXz1IfqDeebaQc/qrwL403zfS4SC6bYZSfAEIkKwGYQIO9BoDX7C97mu2LFHIRe30XeK0=
  on:
    python: '3.6'