language: python

#caching packages
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - pip install --upgrade setuptools wheel
  - pip install -r requirements.txt -r tests/tests-requirements.txt
  - pip install -U .
  - pip freeze

install:
  - python setup.py develop

script:
  - pytest