language: python

#caching packages
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"
  - "3.6"

before_install:
  - pip install --upgrade setuptools wheel
  - pip install -U -r requirements.txt -r tests/tests-requirements.txt

install:
  - python setup.py develop

# pytest configuration is in pytest.ini
script:
  - pytest --cov=perfcounters --capture=sys

after_success:
  - coveralls